// <auto-generated />
namespace APIMVCLearning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adddescriptionuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddescriptionuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131710154_add-description-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
